version: 0.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
before_build:
  dotnet restore
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
deploy:
  provider: NuGet
  api_key:
    secure: x6RcBvyLLANc1CyznRWeSmmF0mOju+qCBpvUeVFpmCIuLk4MolWzwHOucI8tYtHJ
  skip_symbols: false
  artifact: /Meraki\.Dashboard\.\d+\.\d+\.\d+\.nupkg/