version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
  - master
environment:
  COVERALLS_REPO_TOKEN:  
    secure: P3EVIIDPJHR1b5mQCxj6jYncHUeoYDcXhhBc9IfI7UqOKYRF45RftY4y/1S6P/PO
before_build:
  dotnet restore src/Meraki.Dashboard.sln
build:
  project: src/Meraki.Dashboard.sln
  verbosity: minimal
test_script:
  - cmd: tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"dotnet test" -targetarg:"src\Meraki.Dashboard.Test\Meraki.Dashboard.Test.csproj" -output:coverage.xml
  - cmd: tools\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%